### ISSUE TITLE
同学个人信息记得保护下

### ISSUE THREAD

**Issue by roaming-debug** [pecof/zjnudk#1]
https://github.com/pecof/zjnudk/blob/38bb55776f36602ee1b1e21113e18ca3e7e5ca6c/autosubmit.py#L25-L26

**Comment by pecof** [comment]
感谢提醒~

**Comment by roaming-debug** [comment]
我再提醒下… git 是有修改记录的，[修改地址](https://github.com/pecof/zjnudk/commit/aa9a8741fbaad36824ad8c22ca62c197f34728a8)

**Comment by pecof** [comment]
谢谢啦 发现自己好粗心hhh
